spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/sample
    username: user
    password: password
    db: muscleApplication_db
    type: com.zaxxer.hikari.HikariDataSource